#- name: Get target switch
#  hosts: localhost
#  gather_facts: no
#  vars_prompt:
#  - name: target_host
#    prompt: please enter the target switch hostname or IP
#    private: no
#    tasks:
#    add_host:
#      name: "{{ target_host }}"
#      groups: dynamically_created_hosts

- name: run playbook
  hosts: ios
  gather_facts: yes
  roles:
  - metadata
  - retrieve_running
  - get_interfaces
  - add_helpers
  - report
