variable "environment" {}
variable "Number" {}
variable "ResourceGroupName" {}
variable "IteResourceGroup" {}
variable "location" {}
variable "iteKeyVaultId" {}
variable "subnet_id" {}
variable "tenant_id" {}
variable "object_id" {}
variable "sqlAdminPw" {}
