variable "environment" {}
variable "HospNumber" {}
variable "VmSize" {}
variable "VmCount" {}
variable "VmSku" {}
variable "IteResourceGroup" {}
variable "location" {}
variable "vNetSpace" {}
variable "subnet" {}
variable "IteKeyVaultName" {}
variable "dsc_endpoint" {}
variable "dsc_key" {}
